name: HomePlugin2
version: '${project.version}'
main: home.plugin.homeplugin2.HomePlugin2
api-version: '1.20'
commands:
  home:
    description: Sends player to respawn location.
    permission: homeplugin.home